In [1]:
import numpy as np
import aocd
import re

In [2]:
test_input = """Button A: X+94, Y+34
Button B: X+22, Y+67
Prize: X=8400, Y=5400

Button A: X+26, Y+66
Button B: X+67, Y+21
Prize: X=12748, Y=12176

Button A: X+17, Y+86
Button B: X+84, Y+37
Prize: X=7870, Y=6450

Button A: X+69, Y+23
Button B: X+27, Y+71
Prize: X=18641, Y=10279"""

In [3]:
def parse_input(puzzle_input):
    numbers = np.array(re.findall(r'\b\d+\b', puzzle_input)).astype(int)
    machines = []
    for i in range(0, len(numbers), 6):
        machines.append({"A": np.array(numbers[i:i+2]), "B": np.array(numbers[i+2:i+4]), "Target": np.array(numbers[i+4:i+6])})
    return machines

In [20]:
machines= parse_input(test_input)

In [21]:
machine = machines[0]

In [22]:
A = np.hstack( [machine["A"].reshape(-1, 1), machine["B"].reshape(-1,1)])

In [23]:
A

array([[94, 22],
       [34, 67]])

In [24]:
Ai = np.linalg.inv(A)

In [25]:
T = machine["Target"]

In [33]:
x = np.dot(Ai, T).astype(float)

In [35]:
x == x.astype(np.int64)

array([ True, False])

In [37]:
c = x * [3,1]

In [39]:
c = sum(c)

In [40]:
c == int(c)

np.True_

In [13]:
B = np.array([118.4, 135.2])
A = np.array([[3, 3.2],[3.5, 3.6]])

In [14]:
Ai = np.linalg.inv(A)

In [15]:
x = np.dot(Ai,B)

In [16]:
x.dtype

dtype('float64')

In [17]:
A.dtype

dtype('float64')

In [18]:
A

array([[3. , 3.2],
       [3.5, 3.6]])

In [431]:
def parse_input(puzzle_input):
    numbers = np.array(re.findall(r'\b\d+\b', puzzle_input)).astype(np.float64)
    machines = []
    for i in range(0, len(numbers), 6):
        machines.append({"A": np.array(numbers[i:i+2]), "B": np.array(numbers[i+2:i+4]), "Target": np.array(numbers[i+4:i+6])})
    return machines

In [435]:
def solve_machine(machine, offset = False):
    Arr = np.hstack( [machine["A"].reshape(-1, 1), machine["B"].reshape(-1,1)],dtype=np.float64)
    T = machine["Target"]
    if offset:
        T = np.array([T[0]+10000000000000, T[1]+10000000000000], dtype = np.float64)
    Arr_i = np.linalg.inv(Arr)
    A, B = np.dot(Arr_i, T)
    if np.round(A,3).is_integer() and np.round(B, 3).is_integer():
        return A*3+B
    return 0

In [438]:
def solve_machines(puzzle_input):
    machines = parse_input(puzzle_input)
    print(f"Gambling on {len(machines)} machines")
    spent = 0
    prizes = 0
    for i, m in enumerate(machines):
        spent+=solve_machine(m, offset = True)
    return int(spent)
        

In [439]:
solve_machines(puzzle_input)

Gambling on 320 machines


94955433618919

In [338]:
machines = parse_input(test_input)

In [339]:
puzzle_input = aocd.get_data()

In [340]:
tokens_spent = solve_machines(puzzle_input)

Gambling on 320 machines
Machine 1 results in [1.21654501e+11 5.38755649e+10], giving with a cost of 418839068687.105.  solvable=np.False_ prizes for 0 tokens
Machine 2 results in [1.62601626e+11 8.13008130e+10], giving with a cost of 569105691176.911.  solvable=np.False_ prizes for 0 tokens
Machine 3 results in [2.10016155e+11 1.13085622e+11], giving with a cost of 743134087589.0.  solvable=np.True_ prizes for 743134087589 tokens
Machine 4 results in [1.30293160e+11 1.03642286e+11], giving with a cost of 494521765513.0.  solvable=np.True_ prizes for 1237655853102 tokens
Machine 5 results in [1.52749491e+11 1.05227427e+11], giving with a cost of 563475900343.0.  solvable=np.True_ prizes for 1801131753445 tokens
Machine 6 results in [1.64036545e+11 5.81395349e+10], giving with a cost of 550249169577.216.  solvable=np.False_ prizes for 1801131753445 tokens
Machine 7 results in [1.93027946e+11 5.47392682e+10], giving with a cost of 633823105786.218.  solvable=np.False_ prizes for 18011317

In [341]:
tokens_spent

(95346058619115, 169)

In [342]:
aocd.submit(10000000000000)

answer a: 29711
submitting for part b (part a is already completed)
wrong answer: That's not the right answer.  If you're stuck, make sure you're using the full input data; there are also some general tips on the about page, or you can ask for hints on the subreddit.  Because you have guessed incorrectly 9 times on this puzzle, please wait 10 minutes before trying again. [Return to Day 13]


That's not the right answer.  If you're stuck, make sure you're using the full input data; there are also some general tips on the about page, or you can ask for hints on the subreddit.  Because you have guessed incorrectly 9 times on this puzzle, please wait 10 minutes before trying again. [Return to Day 13]


tokens_spent

In [156]:
x += 10000

In [207]:
x

array([30080., 30040.])

In [209]:
[i.is_integer() for i in x]

[True, True]

In [158]:
import math

In [346]:
def parse_input(puzzle_input):
    numbers = re.findall(r'\b\d+\b', puzzle_input)
    machines = []
    for i in range(0, len(numbers), 6):
        machines.append([int(numbers[i+j]) for j in range(6)])
        # machines.append({"A": np.array(numbers[i:i+2]), "B": np.array(numbers[i+2:i+4]), "Target": np.array(numbers[i+4:i+6])})
    return machines

In [347]:
parse_input(test_input)

[[94, 34, 22, 67, 8400, 5400],
 [26, 66, 67, 21, 12748, 12176],
 [17, 86, 84, 37, 7870, 6450],
 [69, 23, 27, 71, 18641, 10279]]

In [348]:
machines = parse_input(test_input)

In [349]:
button_presses = solve_machine(machines[0], offset = 0)

TypeError: solve_machine() got an unexpected keyword argument 'offset'

In [350]:
(button_presses % 1) == 0

array([ True, False])

In [388]:
tokens

15615857404098.0

In [389]:
machines = parse_input(puzzle_input)

In [422]:
def solve_machine(machine, offset = True):
    Arr = np.array([[machine[0], machine[2]], [machine[1], machine[3]]], dtype=np.float64)
    T = np.array(machine[4:], dtype=np.float64)
    if offset:
        T = np.array([T[0] + 10000000000000, T[1] + 10000000000000], dtype = np.float64)
    A, B = np.dot(np.linalg.inv(Arr), T)
    if np.round(A, 3).is_integer() and np.round(B, 3).is_integer():
        return A*3 + B
    return 0


def solve_machines(puzzle_input, offset =  10000000000000):
    machines = parse_input(puzzle_input)
    print(f"Gambling on {len(machines)} machines")
    spent = 0
    for i, m in enumerate(machines):
        spent+= solve_machine(m, offset) 
        # print(f"Machine {i+1} results in {button_presses}, giving with a cost of {cost}.  {solvable=} prizes for {spent} tokens")
    return spent

In [423]:
spent = solve_machines(puzzle_input)

Gambling on 320 machines


In [424]:
int(spent)

94955433618919

In [421]:
aocd.submit(spent)

answer a: 29711
submitting for part b (part a is already completed)
coerced float64 value np.float64(94955433618919.0) for 2024/13 to '94955433618919'


That's the right answer!  You are one gold star closer to finding the Chief Historian.You have completed Day 13! You can [Shareon
  Bluesky
Twitter
Mastodon] this victory or [Return to Your Advent Calendar].
