In [1]:
import numpy as np
import aocd

In [2]:
puzzle_input = aocd.get_data(day = 3, year = 2019)

In [3]:
test_wire1 = "R8,U5,L5,D3"
test_wre2 = "U7,R6,D4,L4"

In [4]:
directions = {"R": [0, 1],
              "U": [-1, 0],
              "D": [1, 0],
              "L": [0,-1]}
              

In [15]:
def wire_to_coords(wire):
    steps = wire.split(",")
    wire_run = []
    for step in steps:
        d = step[0]
        n = int(step[1:])
        wire_run += int(n) * [directions[d]]
    return np.cumsum(np.vstack([[0,0], wire_run]), axis = 0)
                
                
        

In [16]:
r1 = wire_to_coords(test_wire1)
r2 = wire_to_coords(test_wre2)

In [7]:
overlay = r1[(r1 == r2).all(axis = 1)]

In [8]:
def manhattan_distance(loc):
    return np.sum(abs(loc))

In [9]:
manhattan_distance(overlay[1:])

np.int64(17)

In [49]:
def solve1(data):
    wire1, wire2 = data.split("\n")
    r1 = wire_to_coords(wire1)
    r2 = wire_to_coords(wire2)
    r1s = set([tuple(x) for x in r1])
    r2s = set([tuple(x) for x in r2])
    crossings = r1s.intersection(r2s)
    crossings = [np.array(x) for x in crossings]
    dists = [manhattan_distance(loc) for loc in crossings if sum(loc)!=0]
    return min(dists)

In [50]:
solve1(test_wire1+"\n"+test_wre2)

np.int64(11)

In [79]:
w1 ,w2 = puzzle_input.split("\n")


In [80]:
wire_to_coords(w1)

array([[    0,     0],
       [    0,     1],
       [    0,     2],
       ...,
       [-2793,  7651],
       [-2793,  7650],
       [-2793,  7649]])

In [81]:
solve1(puzzle_input)

np.int64(1211)

## part 2

In [127]:
def solve2(data):
    w1, w2 = data.split("\n")    
    c1 = wire_to_coords(w1)
    c2 = wire_to_coords(w2)
    r1s = set([tuple(x) for x in c1])
    r2s = set([tuple(x) for x in c2])
    crossings = r1s.intersection(r2s)
    crossings = [tuple(x) for x in crossings if not (x[0] == 0 and x[1] == 0)]
    t1 = [tuple(x) for x in c1]
    t2 = [tuple(x) for x in c2]
    dists = []
    for crossing in crossings:
        steps1 = t1.index(crossing)
        steps2 = t2.index(crossing)
        dists.append(steps1+steps2)
    return np.min(dists)

In [128]:
test1 = "R75,D30,R83,U83,L12,D49,R71,U7,L72\nU62,R66,U55,R34,D71,R55,D58,R83"

In [129]:
solve2(test1)

np.int64(610)

In [130]:
solve2(puzzle_input)

np.int64(101386)

In [65]:
np.where(c2 == crossings[0])

(array([  3869,   7106,   7562,  34551,  36281,  37439,  40301,  54114,
         76706,  99232, 102377, 107855, 110633]),
 array([1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]))

In [ ]:
np.argwhere

In [41]:
step = test_wire1.split(",")

In [42]:
step

['R8', 'U5', 'L5', 'D3']