In [436]:
import aocd
import numpy as np

In [437]:
from skimage.measure import label, regionprops
from scipy.ndimage import label as label2

In [438]:
test_data = """RRRRIICCFF
RRRRIICCCF
VVRRRCCFFF
VVRCCCJFFF
VVVVCJJCFE
VVIVCCJJEE
VVIIICJJEE
MIIIIIJJEE
MIIISIJEEE
MMMISSJEEE"""

In [439]:
def parse_input(data): 
    data = np.array([[x for x in line] for line in data.split("\n")])
    return data

In [440]:
image = parse_input(test_data)

In [441]:
def make_numerical(image):
    image2 = image.copy()
    for i, n in enumerate(np.unique(image)):
        image2[image == n] = i+1
    return image2.astype(int)

In [442]:
def label_and_pad(image, conn = 1):
    return(np.pad(label(image, connectivity = conn),  1, "constant", constant_values = [0]))


In [443]:
nim = label_and_pad(make_numerical(image), conn = 1)

In [444]:
nim

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  1,  1,  1,  2,  2,  3,  3,  4,  4,  0],
       [ 0,  1,  1,  1,  1,  2,  2,  3,  3,  3,  4,  0],
       [ 0,  5,  5,  1,  1,  1,  3,  3,  4,  4,  4,  0],
       [ 0,  5,  5,  1,  3,  3,  3,  6,  4,  4,  4,  0],
       [ 0,  5,  5,  5,  5,  3,  6,  6,  7,  4,  8,  0],
       [ 0,  5,  5,  9,  5,  3,  3,  6,  6,  8,  8,  0],
       [ 0,  5,  5,  9,  9,  9,  3,  6,  6,  8,  8,  0],
       [ 0, 10,  9,  9,  9,  9,  9,  6,  6,  8,  8,  0],
       [ 0, 10,  9,  9,  9, 11,  9,  6,  8,  8,  8,  0],
       [ 0, 10, 10, 10,  9, 11, 11,  6,  8,  8,  8,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [445]:
def calculate_fences(puzzle_input, conn = 1):
    mapped = make_numerical(parse_input(puzzle_input))
    regions = label_and_pad(mapped, conn = conn)
    print(np.unique(regions))
    prices_per_region = []
    for species in np.unique(regions):
        edges_for_region = 0
        if species > 0:
            locs = np.argwhere(regions == species)
            for loc in locs:
                loc_edges = 0
                for d in [[-1,0],[1,0],[0,1],[0,-1]]:
                    neighbolur = regions[loc[0]+d[0], loc[1]+d[1]]
                    if neighbour != regions[loc[0], loc[1]]:
                        loc_edges+=1
                edges_for_region+= loc_edges
            # print(f"A region of {species} plants with price {len(locs)} * {edges_for_region} = {len(locs)*edges_for_region}")
                
            prices_per_region.append(edges_for_region*len(locs))
    return sum(prices_per_region)


In [446]:
test_data2 = """OOOOO
OXOXO
OOOOO
OXOXO
OOOOO"""

In [447]:
calculate_fences(test_data2, conn = 1)

[0 1 2 3 4 5]


772

In [448]:
test_data3 = """AAAA
BBCD
BBCC
EEEC"""

In [449]:
calculate_fences(test_data3, conn = 1)

[0 1 2 3 4 5]


140

In [450]:
data = aocd.get_data(year = 2024, day = 12)

In [451]:
price = calculate_fences(data, conn = 1)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [435]:
price

6172928

In [332]:
TEST = np.array([[1,1,0,0],[1,1,0,0],[0,0,1,1],[0,0,1,1]])

In [333]:
label_and_pad(TEST)

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 2, 2, 0],
       [0, 0, 0, 2, 2, 0],
       [0, 0, 0, 0, 0, 0]])

In [334]:
test2 = np.array([[1,0,1],[0,1,0],[1,0,1]])

In [335]:
test2="""ABBBA
BABAB
BBABB
BABAB
ABBBA"""

In [336]:
calculate_fences(test2, conn = 1)

196

In [337]:
data = aocd.get_data(year = 2024, day = 12)

In [338]:
calculate_fences(data, conn = 1)

6172928

This is somehow too high? Also with fixed connectivity? I dont understand it at all and need to implement it from scratch. Maybe with even more image analysis approach? Simple kernels to find edges by concolving?

In [390]:
full_map = parse_input(test_data)

In [391]:
from scipy.signal import convolve2d
from scipy.ndimage import label

In [392]:
def calculate_fence_conv(puzzle_input):
    full_map = parse_input(puzzle_input)
    fence_price = 0
    for garden_map, n_regions in [label(full_map == plant) for plant in np.unique(full_map)]:
        for region in range(1, n_regions+1):
            garden = (garden_map == region)
            horizontal_edges = np.abs(convolve2d(garden, [[1, -1]]))
            vertical_edges = np.abs(convolve2d(garden, [[1], [-1]]))
            fence_price+= garden.sum() * (horizontal_edges.sum() + vertical_edges.sum())
    return fence_price

In [393]:
fence_price

np.int64(1396298)

In [394]:
fence_price = calculate_fence_conv(data)

In [395]:
fence_price

np.int64(1396298)

In [396]:
# aocd.submit(fence_price)

answer a: 1396298
submitting for part b (part a is already completed)
coerced int64 value np.int64(1396298) for 2024/12 to '1396298'


aocd will not submit that answer. At 2024-12-12 13:14:18.270441-05:00 you've previously submitted 853588 and the server responded with:
That's the right answer!  You are one gold star closer to finding the Chief Historian.You have completed Day 12! You can [Shareon
  Bluesky
Twitter
Mastodon] this victory or [Return to Your Advent Calendar].
It is certain that '1396298' is incorrect, because '1396298' != '853588'.


for part two we need to find corners. Corner Kernel?

In [416]:
kernel = np.array([[1,-1], [-1, 1]])

In [417]:
kernel

array([[ 1, -1],
       [-1,  1]])

In [418]:
r = np.array([[0,0,0,0],[0,1,1,1],[0,0,1,1],[0,0,0,1]])

In [419]:
r #weird 8 corner shape

array([[0, 0, 0, 0],
       [0, 1, 1, 1],
       [0, 0, 1, 1],
       [0, 0, 0, 1]])

In [420]:
r[:2, :2] * kernel

array([[0, 0],
       [0, 1]])

In [421]:
r[2:, 2:] * kernel

array([[ 1, -1],
       [ 0,  1]])

In [422]:
np.abs(convolve2d(r, kernel)).sum()

np.int64(8)

In [423]:
def calculate_fence_conv(puzzle_input):
    full_map = parse_input(puzzle_input)
    fence_price = 0
    for garden_map, n_regions in [label(full_map == plant) for plant in np.unique(full_map)]:
        for region in range(1, n_regions+1):
            garden = (garden_map == region)
            # horizontal_edges = np.abs(convolve2d(garden, [[1, -1]]))
            # vertical_edges = np.abs(convolve2d(garden, [[1], [-1]]))
            corner = np.abs(convolve2d(garden, [[-1, 1], [1, -1]]))
            fence_price+= garden.sum() * (corner.sum())
    return fence_price

In [427]:
calculate_fence_conv(r)

AttributeError: 'numpy.ndarray' object has no attribute 'split'

In [424]:
fence_price2 = calculate_fence_conv(data)

In [425]:
fence_price2

np.int64(853588)

In [426]:
#aocd.submit(fence_price2)