In [1]:
import numpy as np
from aocd import get_data, submit

In [2]:
test_input = """89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732"""

In [176]:
def parse_input(data):
    return np.array([[int(x) for x in line] for line in data.split("\n")])

In [190]:
test_data = parse_input(test_input)

In [191]:
test_data

array([[8, 9, 0, 1, 0, 1, 2, 3],
       [7, 8, 1, 2, 1, 8, 7, 4],
       [8, 7, 4, 3, 0, 9, 6, 5],
       [9, 6, 5, 4, 9, 8, 7, 4],
       [4, 5, 6, 7, 8, 9, 0, 3],
       [3, 2, 0, 1, 9, 0, 1, 2],
       [0, 1, 3, 2, 9, 8, 0, 1],
       [1, 0, 4, 5, 6, 7, 3, 2]])

In [192]:
test_data = np.pad(test_data, 1, "constant", constant_values = [-1])

In [193]:
test_data

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1,  8,  9,  0,  1,  0,  1,  2,  3, -1],
       [-1,  7,  8,  1,  2,  1,  8,  7,  4, -1],
       [-1,  8,  7,  4,  3,  0,  9,  6,  5, -1],
       [-1,  9,  6,  5,  4,  9,  8,  7,  4, -1],
       [-1,  4,  5,  6,  7,  8,  9,  0,  3, -1],
       [-1,  3,  2,  0,  1,  9,  0,  1,  2, -1],
       [-1,  0,  1,  3,  2,  9,  8,  0,  1, -1],
       [-1,  1,  0,  4,  5,  6,  7,  3,  2, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]])

In [194]:
starting_positions = np.argwhere(test_data == 0)

In [195]:
list(starting_positions)

[array([1, 3]),
 array([1, 5]),
 array([3, 5]),
 array([5, 7]),
 array([6, 3]),
 array([6, 6]),
 array([7, 1]),
 array([7, 7]),
 array([8, 2])]

In [196]:
test_data.take(starting_positions[0])

array([-1, -1])

In [197]:
test_data.shape

(10, 10)

In [198]:
##this smells of recursion, breath-first-search stuff....

In [219]:
def walk(x,y, data):
    path = [(x,y)]
    tops = set() #we are only collecting unique tops reached
    while path:
        x, y = path.pop() #get last path position
        if (height := data[x,y]) == 9: #if it is 9 we are at a top
            tops.add((x,y))
        if data[x-1, y] == height+1: #up
            path.append((x-1, y))
        if data[x+1, y] == height+1: #down
            path.append((x+1, y))
        if data[x, y+1] == height+1: #right
            path.append((x, y+1))
        if data[x, y-1] == height+1: #left
            path.append((x, y-1))
    return len(tops)

In [220]:
def find_trailhead_paths(puzzle_input):
    data = parse_input(puzzle_input)
    data =  np.pad(data, 1, "constant", constant_values = [-1])
    start_positions = np.argwhere(data == 0)
    total_score = 0
    for sp in start_positions:
        total_score += walk(sp[0], sp[1], data)
    return total_score


In [221]:
find_trailhead_paths(test_input)

36

In [212]:
find_trailhead_paths(get_data(day=10, year=2024))

667

## part two
Just swap the set with a list?

In [227]:
def walk(x,y, data):
    path = [(x,y)]
    tops = [] #we want to know about every time we reach a top through some route
    while path:
        x, y = path.pop()
        if (height := data[x,y]) == 9:
            tops.append((x,y))
        if data[x-1, y] == height+1: #up
            path.append((x-1, y))
        if data[x+1, y] == height+1: #down
            path.append((x+1, y))
        if data[x, y+1] == height+1: #right
            path.append((x, y+1))
        if data[x, y-1] == height+1: #left
            path.append((x, y-1))
    return len(tops)

In [228]:
find_trailhead_paths(test_input)

81

In [229]:
find_trailhead_paths(get_data(day=10, year=2024))

1344